### ISSUE TITLE
Build a collection of gadgets?

### ISSUE THREAD

**Issue by acorncom** [rtablada/inspector-gadget#1]
Hi Ryan, I'm straddling the Ember / Laravel world with you and was glad to see this repo :-)

Before Laravel hit in a major way, I was using an older framework called Yii.  It's the only framework I've run into that uses components in a major way on the backend.  They call them widgets (more details here: http://www.yiiframework.com/doc/guide/1.1/en/basics.view#widget) and they enjoy first-class framework support.

One of their nicer widgets is visible here: http://www.yiiframework.com/doc/api/1.1/CGridView

Would you be interested in replicating those types of gadgets here?  I've got clients using Laravel who need this type of the thing and it's one of the areas I sorely miss from Yii at the moment ...

**Comment by rtablada** [comment]
I would say that this package is focused on the underlying gadget tool and not implementations of rendered classes.

I would love to see this package used as a dependency for things like data grids or pagination, and would consider listing implementations in the readme or other docs.

—

**Comment by acorncom** [comment]
Sounds good, if I get around to it, I'll let you know :-)
